name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.6
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5



    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108

      - name: Install PostgreSQL
        run: sudo apt-get -yqq install libpq-dev

      - name: Run bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: mbent
        run: bin/rails db:setup

      - name: Build and test with rspec
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: mbent
        run: bundle exec rspec spec

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "railsmusiclibapp"
          heroku_email: "bentkowskimaciej@gmail.com"
